sudo: false
language: node_js
node_js:
- 6
- node
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
notifications:
  slack:
    rooms:
      secure: ml4venada7c/1QHqWOQury/CFkqXHWPqBggKr4Xl/RIiYGiA5R/9TzKI3XTDQIM2ql30N7ixVgWmxoXTfbEKgkmf7wElfdieRx3le6mCxKdAIVQTZAquRyCb9PfSQZf7S3R7s0lczuUXwtlCFY+jlgoI37E63zZOnUqN5bJsUVPax98sSRrIw8bni51jUiItiEFb2iL9WIz75l/XmoQRJMaDUZOKWr2jfMM28+rZW92SaUdQALkVRosYCXhWlJkUL2QhUgKQJmwJw8P1F42uDJxsW7QtS8ZK45l/MNJGEwzkDZUU577a8nvO/7N1ljW9zt6xPIbHMIjE+1mujOG49q03G/8LaX8bIyb1zW+yAOhGFOsXPPmHzEnFG+YuuLosHdOa/eSl38Tqc51ZoaK73GrpK1r8CaM88BdE6uJB0PxKniiN2L+qodKipySPpB5mWKw6+gXnaRjZOw0STWQGZYDwbw6XMM3HGZynf+es/9eQHxBWSmCMRE0MhDVB3trEljRLi0+m4NYLb1xOW9V6u8T/Bj9FctdURy5Hxtbtj7OWnodJS0M6GJkZnd8dkWjf16FyHgJpFMHKr4KxBBRzT1f1OG2rfhupZ17/9dfdLnqx2kWJY2ZoJ7RI+Hr1luB2sPAT91cvTHGV59J+5anRqxdInsDN55oZOECc/XpdViQ=
